/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * RecognizeFrame.java
 *
 * Created on 2010-04-15, 09:34:05
 */

package pl.umk.mat.imare.gui;

import java.awt.Component;
import pl.umk.mat.imare.reco.Recognizer;

/**
 *
 * @author morti
 */
public class RecognizeFrame extends javax.swing.JInternalFrame {

	private MainGUI mainWindow;

    /** Creates new form RecognizeFrame */
    public RecognizeFrame() {
        initComponents();
		recognizerOptionsPanel1.setShowRestoreDefaultsButton(false);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        recognizerOptionsPanel1 = new pl.umk.mat.imare.gui.RecognizerOptionsPanel();
        recognizeButton = new javax.swing.JButton();
        defaultsButton = new javax.swing.JButton();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Ustawienia Rozpoznawania");
        addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                formAncestorAdded(evt);
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        recognizeButton.setText("Rozpocznij Rozpoznawanie");
        recognizeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                recognizeButtonActionPerformed(evt);
            }
        });

        defaultsButton.setText("Przywróć domyślne");
        defaultsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defaultsButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(recognizerOptionsPanel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 554, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(defaultsButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 195, Short.MAX_VALUE)
                        .addComponent(recognizeButton)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(recognizerOptionsPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(recognizeButton)
                    .addComponent(defaultsButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

	private void recognizeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_recognizeButtonActionPerformed
		Recognizer reco = recognizerOptionsPanel1.getRecognizer(mainWindow.getOpenedWave());
		RecognitionProgress prog = new RecognitionProgress(reco, true);
		getDesktopPane().add(prog);
		prog.setVisible(true);
		reco.start();
	}//GEN-LAST:event_recognizeButtonActionPerformed

	private void formAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_formAncestorAdded
		Component c = getDesktopPane();
		while(!(c instanceof MainGUI) && c != null) c = c.getParent();

		if(c != null) {
			mainWindow = (MainGUI)c;
		}
	}//GEN-LAST:event_formAncestorAdded

	private void defaultsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defaultsButtonActionPerformed
		recognizerOptionsPanel1.restoreDefaults();
	}//GEN-LAST:event_defaultsButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton defaultsButton;
    private javax.swing.JButton recognizeButton;
    private pl.umk.mat.imare.gui.RecognizerOptionsPanel recognizerOptionsPanel1;
    // End of variables declaration//GEN-END:variables

}
