/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * LicenseDialog.java
 *
 * Created on 2010-11-29, 17:40:18
 */

package pl.umk.mat.imare.gui;

/**
 *
 * @author morti
 */
public class LicenseDialog extends javax.swing.JDialog {

    /** Creates new form LicenseDialog */
    public LicenseDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        this.setTitle("Licencja");
        initComponents();
        setLocationRelativeTo(null);

    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
  // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
  private void initComponents() {

    jScrollPane1 = new javax.swing.JScrollPane();
    jTextPane1 = new javax.swing.JTextPane();
    jButton1 = new javax.swing.JButton();

    setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

    jTextPane1.setEditable(false);
    jTextPane1.setText("Marcin Radoszewski, Piotr Różański, Mariusz Tycz, Maciej Włoch, Bartosz Zasada © 2010\nPrawa autorskie zastrzeżone.\n\nNiniejszym udziela się bezpłatnie, każdej osobie uzyskującej kopię tego oprogramowania i/lub powiązanych plików dokumentacji (Oprogramowania), praw do nielimitowanego używania i rozprowadzania Oprogramowania w niezmienionej postaci, z zastrzeżeniem następujących warunków:\n\nPowyższe informacje o prawach autorskich oraz niniejsza nota zezwalająca muszą zostać włączone w wszystkich egzemplarzach Oprogramowania.\n\nOprogramowanie jest dostarczane bez jakichkolwiek gwarancji, wyrażonych wprost lub w domyśle. W żadnym wypadku autorzy lub właściciele praw autorskich nie będą odpowiedzialni za jakiekolwiek szkody czy zaniedbania związane bezpośrednio lub pośrednio z działaniem Oprogramowania.\n"); // NOI18N
    jScrollPane1.setViewportView(jTextPane1);

    jButton1.setText("Zamknij");
    jButton1.addActionListener(new java.awt.event.ActionListener() {
      public void actionPerformed(java.awt.event.ActionEvent evt) {
        jButton1ActionPerformed(evt);
      }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(layout.createSequentialGroup()
        .addContainerGap()
        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
          .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING)
          .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 501, Short.MAX_VALUE))
        .addContainerGap())
    );
    layout.setVerticalGroup(
      layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
      .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
        .addContainerGap()
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 308, Short.MAX_VALUE)
        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
        .addComponent(jButton1)
        .addContainerGap())
    );

    pack();
  }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LicenseDialog dialog = new LicenseDialog(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

  // Variables declaration - do not modify//GEN-BEGIN:variables
  private javax.swing.JButton jButton1;
  private javax.swing.JScrollPane jScrollPane1;
  private javax.swing.JTextPane jTextPane1;
  // End of variables declaration//GEN-END:variables

}
